### ISSUE TITLE
"Your Nominations" Throws Application Error (Sometimes?)

### ISSUE THREAD

**Issue by kelind** [antialiasis/serebii-fanfic-awards#36]
The "Your Nominations" page is taking an awful long time to load (~10 seconds) for me, and 5/6 times it's thrown an application error when I tried to load it. First time I tried it, I had no nominations yet, and I got an application error. I tried again and was able to get in and submit my nominations successfully. However, I have since not been able to access the page due to application errors, which is making it difficult for me to correct an embarrassing mistake in one of my noms. >>

**Comment by kelind** [comment]
I logged out and logged back in and was able to edit my nominations, but it was still very slooooow.

**Comment by antialiasis** [comment]
Is it better now? I wasn't getting the kinds of delays you described, but now it should not be evaluating the queryset that gets the currently-nominated fics as often.

The application errors were almost definitely simply timeouts, if things were being slow - Heroku is pretty merciless on noping out if things are taking too long.

**Comment by kelind** [comment]
Yeah, I think that did the trick.
